const dateFormatConfig = {
    dayNames: [
        "Dom",
        "Lun",
        "Mar",
        "Mierc",
        "Juev",
        "Viern",
        "Sab",
        "Domingo",
        "Lunes",
        "Martes",
        "Miercoles",
        "Jueves",
        "Viernes",
        "Sabado",
    ],
    monthNames: [
        "Ene",
        "Feb",
        "Mar",
        "Abr",
        "May",
        "Jun",
        "Jul",
        "Agos",
        "Sep",
        "Oct",
        "Nov",
        "Dec",
        "Enero",
        "Febrero",
        "Marzo",
        "Abril",
        "Mayo",
        "Junio",
        "Julio",
        "Agosto",
        "Septiembre",
        "Octubre",
        "Noviembre",
        "Diciembre",
    ],
    timeNames: ["a", "p", "am", "pm", "A", "P", "AM", "PM"],
};

module.exports.dateFormatConfig = dateFormatConfig;